const {Router} = require('express')
const router = Router()
const NewsController = require('../controllers/views.controller')
const authMiddlewere = require("../middlewere/auth.middlewere");
const SkillController = require("../controllers/skill.controller");

router.get('/news',NewsController.getNews)
router.post('/createpost',authMiddlewere,NewsController.createPost)
router.post('/plusaup',authMiddlewere,NewsController.plusAUP)
router.post('/updatemanaup',authMiddlewere,NewsController.updateManAUP)
router.get('/getaup',NewsController.getAUP)
router.post('/delman',authMiddlewere,NewsController.delMan)
router.post('/plusvideo',authMiddlewere,NewsController.plusVideo)
router.post('/pluscomvak',authMiddlewere,NewsController.plusComVak)
router.post('/getcomvak',authMiddlewere,NewsController.getComVak)
router.post('/editopenvak',authMiddlewere,NewsController.editOpenVak)
router.post('/delcomvak',authMiddlewere,NewsController.delComVak)
router.post('/createvak',authMiddlewere,NewsController.createVak)
router.get('/getvakansii',authMiddlewere,NewsController.getVakansii)
router.post('/editvak',authMiddlewere,NewsController.editVak)
router.post('/deltisvak',authMiddlewere,NewsController.delTisVak)
router.post('/getabout',authMiddlewere,NewsController.getAbout)
router.post('/saveabout',authMiddlewere,NewsController.saveAbout)
router.post('/pluscompany',authMiddlewere,NewsController.plusCompany)
router.get('/getgroupcompanyes',authMiddlewere,NewsController.getGroupCompanyes)
router.post('/delcomgroup',authMiddlewere,NewsController.delComGroup)
router.post('/editcomgroup',authMiddlewere,NewsController.editСomGroup)
router.post('/updateposcomgroup',authMiddlewere,NewsController.updatePosComGroup)
router.post('/getplaces',authMiddlewere,NewsController.getPlaces)
router.post('/plusplaces',authMiddlewere,NewsController.plusPlaces)
router.post('/delplace',authMiddlewere,NewsController.delPlace)
router.post('/createPack',authMiddlewere,NewsController.createpack)
router.post('/getallpacks',authMiddlewere,NewsController.getAllPacks)
router.post('/editpriorypack',authMiddlewere,NewsController.editPrioryPack)
router.post('/updatepack',authMiddlewere,NewsController.updatePack)
router.post('/createimggallery',authMiddlewere,NewsController.createImgGallery)
router.post('/getgalleryimgs',authMiddlewere,NewsController.getGalleryImgs)
router.post('/deleteimggalary',authMiddlewere,NewsController.deleteImgGalary)
router.post('/getcities',authMiddlewere,NewsController.getCities)
router.post('/createcity',authMiddlewere,NewsController.createCity)
router.post('/uploadstaticcontact',authMiddlewere,NewsController.uploadStaticContact)
router.post('/pluscontactparam',authMiddlewere,NewsController.plusContactParam)
router.post('/createzone',authMiddlewere,NewsController.createZone)
router.post('/getzones',authMiddlewere,NewsController.getZones)
router.post('/updatezone',authMiddlewere,NewsController.updateZone)
router.post('/pluszoneslider',authMiddlewere,NewsController.plusZoneSlider)
router.post('/getzonesslides',authMiddlewere,NewsController.getZonesSlides)
router.post('/editprioryzoneslider',authMiddlewere,NewsController.editPrioryZoneSlider)
router.post('/delzoneslider',authMiddlewere,NewsController.delZoneSlider)
router.post('/getprogramsslides',authMiddlewere,NewsController.getProgramsSlides)
router.post('/plusprogramslider',authMiddlewere,NewsController.plusProgramSlider)
router.post('/delprogramslider',authMiddlewere,NewsController.delProgramSlider)
router.post('/getprogramspage',authMiddlewere,NewsController.getProgramsPage)
router.post('/plusprogrampage',authMiddlewere,NewsController.plusProgramPage)
router.post('/delprogrampage',authMiddlewere,NewsController.delProgramPage)
router.post('/plustrenersgroup',authMiddlewere,NewsController.plusTrenersGroup)
router.post('/gettrenersgroup',authMiddlewere,NewsController.getTrenersGroup)
router.post('/deltrenersgroup',authMiddlewere,NewsController.delTrenersGroup)
router.post('/plustrenerman',authMiddlewere,NewsController.plusTrenerMan)
router.post('/gettrenersman',authMiddlewere,NewsController.getTrenersMan)
router.post('/deltrenerman',authMiddlewere,NewsController.delTrenerMan)
router.post('/delpacks',authMiddlewere,NewsController.delPacks)
router.post('/getmobileurls',authMiddlewere,NewsController.getMobileURLs)
router.post('/updateurlmobileapp',authMiddlewere,NewsController.updateURLMobileAPP)
router.post('/getallpticesavia',authMiddlewere,NewsController.getAllPticesAvia)
router.post('/getprogramsavia',authMiddlewere,NewsController.getProgramsAvia)
router.post('/createpriceavia',authMiddlewere,NewsController.createPriceAvia)
router.post('/editpriceavia',authMiddlewere,NewsController.editPriceAvia)
router.post('/delprice',authMiddlewere,NewsController.delPrice)
router.post('/delnewspost',authMiddlewere,NewsController.delNewsPost)
router.post('/updatepost',authMiddlewere,NewsController.updatePost)
router.post('/reverseprioryaup',authMiddlewere,NewsController.reversePrioryAUP)
router.post('/editprioryprice',authMiddlewere,NewsController.editPrioryPrice)
router.post('/createteacheravia',authMiddlewere,NewsController.createTeacherAvia)
router.post('/getteachersavia',authMiddlewere,NewsController.getTeachersAvia)
router.post('/prioryteachersavia',authMiddlewere,NewsController.prioryTeachersAvia)
router.post('/editteacheravia',authMiddlewere,NewsController.editTeacherAvia)
router.post('/delteacheravia',authMiddlewere,NewsController.delTeacherAvia)
router.post('/getlearnteory',authMiddlewere,NewsController.getLearnTeory)
router.post('/edittheorydesc',authMiddlewere,NewsController.editTheoryDesc)
router.post('/createlistleart',authMiddlewere,NewsController.createListLeart)
router.post('/createlisttheory',authMiddlewere,NewsController.createListTheory)


module.exports = router